apiVersion: v1
kind: Pod
metadata:
  labels:
    run: color-api-pod
  name: color-api-pod
spec:
  containers:
  - image: lironefitoussi/color-api:1.0.0
    name: color-api-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}